### ISSUE TITLE
NICがPrivate address, Global address とついている場合sshにPrivate address使われることがある

### ISSUE THREAD

**Issue by naototty** [hironobu-s/novassh#2]
NICがPrivate address, Global address とついている場合、novassh --list でprivate addressだけ表示され、それがsshに利用されることがある。

  * openstack.goのソースを見て、思いましたが、novassh自体がglobal address で使われない場合(NATがある環境で、NAT配下のVMの場合、 private network構成 でもnovassh が使われることがある(踏み台サーバなどのご利用))ことを思いつきましたので、必ずしもpublic をsshの接続先にするひつようは無いと思います。
 
### いまは、どちらが表示されるのか、叩くたびに異なります。

```
(openstack)[n-gohko@ce7x-console API-test-env(ent-main-test-ze#2)]$ novassh --list | grep -E '(Name|gohko)'
[Name]                                  [IP Address]
gohko-ce74-test01                       150.95.35.45

(openstack)[n-gohko@ce7x-console API-test-env(ent-main-test-ze#2)]$ novassh --list | grep -E '(Name|gohko)'
[Name]                                  [IP Address]
gohko-ce74-test01                       10.10.10.250
```

### 実装をどうするのか、ですが、素直にip addressの複数表示、オプション指定など考えられます

```
(openstack)[n-gohko@ce7x-console API-test-env(ent-main-test-ze#2)]$ novassh --list | grep -E '(Name|gohko)'
[Name]                                  [IP Address]
gohko-ce74-test01                       10.10.10.250,150.95.35.45
```

ex) たとえば、こんな感じで指定できるように
```
novassh --ip 10.10.10.250 root@gohko-ce74-test01
```

ssh コマンドだと下記のようなオプションになりますので、真似る必要は無いと思います。

```
ssh -oHostName=192.168.137.11 root@centos7
```

**Comment by hironobu-s** [comment]
@naototty 
調べてみますー

**Comment by hironobu-s** [comment]
@naototty 
IPアドレスを指定するなら普通にsshコマンドを使うのと変わらなくなってしまうのが難しいところでして。

なので、```NOVASSH_INTERFACE``` と言う環境変数を追加しました。
このオプションで使うNICを固定できます。
```--debug``` オプションでNICの一覧が表示されます。

https://github.com/hironobu-s/novassh#3-3-debug-output

**Comment by naototty** [comment]
buildして使ってみました。
指定のnetwork Portに接続できるようになったので、仕事がはかどります。

**Comment by hironobu-s** [comment]
@naototty  (๑•̀ㅂ•́)و✧
